# Generated by Django 5.2.2 on 2025-06-10 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_theatre_manager',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
