# Generated by Django 5.2.2 on 2025-06-16 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_is_theatre_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp_expired',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
