# Generated by Django 5.2.2 on 2025-06-30 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theaters', '0003_showtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
    ]
