# Generated by Django 5.2.2 on 2025-06-30 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('theaters', '0003_showtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingseat',
            name='showtime',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='theaters.showtime'),
        ),
    ]
